ARG BASE_IMAGE=flagfft-ubuntu2404:latest
FROM ${BASE_IMAGE}

ARG DEBIAN_FRONTEND=noninteractive
ARG GIT_URL_REWRITE_FROM=https://github.com/
ARG GIT_URL_REWRITE_TO=
ARG OHMYZSH_INSTALL_URL=https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
ARG NVM_INSTALL_URL=https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh
ARG NPM_REGISTRY=https://registry.npmmirror.com

SHELL ["/bin/bash", "-lc"]

ENV PYENV_ROOT=/root/.pyenv
ENV PATH=${PYENV_ROOT}/bin:${PYENV_ROOT}/shims:/usr/local/cuda/bin:${PATH}
ENV CUDA_HOME=/usr/local/cuda
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH}
ENV ZSH=/root/.oh-my-zsh
ENV NVM_DIR=/root/.nvm

RUN if [ -n "${GIT_URL_REWRITE_TO}" ]; then \
        git config --global url."${GIT_URL_REWRITE_TO}".insteadOf "${GIT_URL_REWRITE_FROM}"; \
    fi

# zsh
RUN apt-get update && apt-get install -y --no-install-recommends \
    zsh \
    && rm -rf /var/lib/apt/lists/*

RUN chsh -s $(which zsh)

RUN sh -c "$(curl -fsSL ${OHMYZSH_INSTALL_URL})" "" --unattended

RUN ZSH_CUSTOM=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom} && \
    PLUGIN_DIR="$ZSH_CUSTOM/plugins/zsh-autosuggestions" && \
    git clone https://github.com/zsh-users/zsh-autosuggestions $PLUGIN_DIR && \
    sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions)/' ~/.zshrc

# pyenv init for zsh
RUN echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc && \
    echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc && \
    echo 'eval "$(pyenv init - zsh)"' >> ~/.zshrc

# nodejs and codex
RUN curl -o- ${NVM_INSTALL_URL} | bash && \
    . "$HOME/.nvm/nvm.sh" && \
    nvm install 24 && \
    npm install -g @openai/codex --registry=${NPM_REGISTRY}

RUN echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.zshrc && \
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.zshrc && \
    echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> ~/.zshrc

WORKDIR /workspace

CMD ["/bin/zsh"]
